# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bXY4FcH_6TGHJ1uk5OK3xsuJ8RIC4df_
"""

def sum_two_numbers(x, y):
    return x + y
# Random example
x = 9
y = 1
result = sum_two_numbers(x, y)
print(result)

def sum_three_numbers(x, y, z):
    return x + y + z
# Random example
x = 10
y = 20
z = 30
result = sum_three_numbers(x, y, z)
print(result)

def find_max(items):
    return max(items)
# Given list
items = [3, 5, 1, 6, 99, 6]
result = find_max(items)
print(result)

def find_min(items):
    return min(items)
# Given list
items = [3, 5, 1, 6, 99, 6]
result = find_min(items)
print(result)